# Generated by Django 5.1.2 on 2025-02-02 16:22

from django.db import migrations


class Migration(migrations.Migration):
    def add_price_for_old_orders(apps, schema_editor):
        OrderItem = apps.get_model('foodcartapp', 'OrderItem')
        for item in OrderItem.objects.select_related('product').iterator():
            item.price = item.product.price
            item.save()

    dependencies = [
        ('foodcartapp', '0039_alter_order_managers_orderitem_price'),
    ]

    operations = [
        migrations.RunPython(add_price_for_old_orders),
    ]
