# Generated by Django 5.1.2 on 2025-02-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_auto_20250202_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Необработанный'), ('prc', 'Готовится'), ('ind', 'В доставке'), ('cls', 'Заказ закрыт'), ('cnc', 'Заказ отменен')], db_index=True, default='new', max_length=3, verbose_name='Статус'),
        ),
    ]
