# Generated by Django 5.1.2 on 2025-02-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_order_called_at_order_delivery_at_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='order',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Электронно'), ('cash', 'Наличные')], db_index=True, default='card', max_length=4, verbose_name='Способ оплаты'),
        ),
    ]
